### ISSUE TITLE
Partner's Killler drops Partner's head if you kill them

### ISSUE THREAD

**Issue by JawadJ** [stefan-cooper/SpigotUHC#72]
If you kill the killer of your partner, you get the head of your partner back (even if they used it for a golden apple), it would incentivise the person to try and make a play, targeting the person who killed your partner so you can revive them

**Comment by stefan-cooper** [comment]
I like this idea, but it does present a problem. Ideally, we don't want to drop 2 heads on death. So which do we choose, the player who died or the player you want to be revived? If you only drop the latter it is kind of BS for the teammate of that guy that died.

A solution to this could be that we could allow a revive with 'any' head that you find, not just your teammates. That would incentivize going and killing anyone, rather than just the team that killed your teammate. wdyt?
